# CREATED USING EXTERNAL TWEAKER 


import minetweaker.item.IItemStack;
val DCham = <DraconicEvolution:teleporterMKI>;
val plateInfinity = <ore:plateInfinity>;
plateInfinity.add(<ChaosGod:Infinity2>);

val plateCosmicNeutronium = <ore:plateCosmicNeutronium>;
plateCosmicNeutronium.add(<GTFei:Plate5>);

mods.avaritia.ExtremeCrafting.remove(<Avaritia:Orb_Armok>);
mods.avaritia.ExtremeCrafting.addShaped(<magicalcrops:DraconiumSeeds>, [[null,null,null,null,null,null,null,null,null],  [null, <DraconicEvolution:draconiumFluxCapacitor>, <DraconicEvolution:draconium>, <DraconicEvolution:wyvernCore>, null, <DraconicEvolution:wyvernCore>, <DraconicEvolution:draconium>, <DraconicEvolution:draconiumFluxCapacitor>, null],  [null, <DraconicEvolution:draconium>, <DraconicEvolution:draconiumIngot>, <customthings:item:11>, <customthings:item:10>, <customthings:item:11>, <DraconicEvolution:draconiumIngot>, <DraconicEvolution:draconium>, null],  [null, <DraconicEvolution:wyvernCore>, <customthings:item:11>, <customthings:item:13>, <customthings:item:12>, <customthings:item:13>, <customthings:item:11>, <DraconicEvolution:wyvernCore>, null],  [null,null, <customthings:item:10>, <customthings:item:12>, <magicalcrops:FluixSeeds>, <customthings:item:12>, <customthings:item:10>, null,null],  [null, <DraconicEvolution:wyvernCore>, <customthings:item:11>, <customthings:item:13>, <customthings:item:12>, <customthings:item:13>, <customthings:item:11>, <DraconicEvolution:wyvernCore>, null],  [null, <DraconicEvolution:draconium>, <DraconicEvolution:draconiumIngot>, <customthings:item:11>, <customthings:item:10>, <customthings:item:11>, <DraconicEvolution:draconiumIngot>, <DraconicEvolution:draconium>, null],  [null, <DraconicEvolution:draconiumFluxCapacitor>, <DraconicEvolution:draconium>, <DraconicEvolution:wyvernCore>, null, <DraconicEvolution:wyvernCore>, <DraconicEvolution:draconium>, <DraconicEvolution:draconiumFluxCapacitor>, null],  [null,null,null,null,null,null,null,null,null]]);
mods.avaritia.ExtremeCrafting.addShaped(<Avaritia:Resource_Block:1>, [[<Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>],  [<Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>],  [<Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>],  [<Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>],  [<Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>],  [<Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>],  [<Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>],  [<Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>],  [<Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>]]);
mods.avaritia.ExtremeCrafting.addShaped(<TConstruct:creativeModifier>, [[<gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>],  [<gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>],  [<gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32710>, <gregtech:gt.metaitem.01:32710>, <gregtech:gt.metaitem.01:32710>, <gregtech:gt.metaitem.01:32710>, <gregtech:gt.metaitem.01:32710>, <gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32300>],  [<gregtech:gt.metaitem.01:32300>, <gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32300>],  [<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<Avaritia:Resource:5>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<Avaritia:Resource:5>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,],  [<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,],  [<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<Avaritia:Resource:6>,<Avaritia:Resource:6>,<Avaritia:Resource:6>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,],  [<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<Avaritia:Resource:6>,<Avaritia:Resource:6>,<Avaritia:Resource_Block:1>,<Avaritia:Resource:6>,<Avaritia:Resource:6>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>],  [<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>,<gregtech:gt.metaitem.01:32710>]]);
mods.avaritia.ExtremeCrafting.addShaped(<PEAA:AEGU MK1>, [[<ProjectE:collector_mk3>, <ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>],  [<ProjectE:collector_mk3>, <ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>],  [<ProjectE:collector_mk3>, <ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>],  [<ProjectE:collector_mk3>, <ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>],  [<ProjectE:collector_mk3>, <ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>],  [<ProjectE:collector_mk3>, <ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>],  [<ProjectE:collector_mk3>, <ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>],  [<ProjectE:collector_mk3>, <ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>],  [<ProjectE:collector_mk3>, <ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>,<ProjectE:collector_mk3>]]);
mods.avaritia.ExtremeCrafting.addShaped(<PEAA:AEGU MK2>, [[<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,],  [<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,],  [<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,],  [<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,],  [<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,],  [<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,],  [<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,],  [<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,],  [<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,<PEAA:AEGU MK1>,]]);
mods.avaritia.ExtremeCrafting.addShaped(<PEAA:AEGU MK3>, [[<PEAA:AEGU MK2>, <PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>],  [<PEAA:AEGU MK2>, <PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>],  [<PEAA:AEGU MK2>, <PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>],  [<PEAA:AEGU MK2>, <PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>],  [<PEAA:AEGU MK2>, <PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>],  [<PEAA:AEGU MK2>, <PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>],  [<PEAA:AEGU MK2>, <PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>],  [<PEAA:AEGU MK2>, <PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>],  [<PEAA:AEGU MK2>, <PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>,<PEAA:AEGU MK2>]]);
mods.avaritia.ExtremeCrafting.addShaped(<PEEX:aeguEXMk2_off>, [[<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>],  [<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>],  [<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>],  [<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>],  [<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>],  [<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>],  [<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>],  [<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>],  [<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>,<PEAA:AEGU MK3>]]);
mods.avaritia.ExtremeCrafting.addShaped(<PEEX:aeguEXMK3_off>, [[<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>],  [<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>], [<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>], [<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>], [<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>], [<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>], [<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>], [<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>], [<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>,<PEEX:aeguEXMk2_off>]]);
mods.avaritia.ExtremeCrafting.addShaped(<PEEX:aeguEXFinal_off>, [[<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>],  [<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>],[<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>],[<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>],[<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>],[<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>],[<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>],[<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>],[<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>,<PEEX:aeguEXMK3_off>]]);
mods.avaritia.ExtremeCrafting.addShaped(<customthings:item:49>, [[null,null,null,null,null,null,null,null,null],  [<customthings:item:47>,<customthings:item:29>,<customthings:item:29>,<customthings:item:29>,<customthings:item:29>,<customthings:item:29>,<customthings:item:29>,<customthings:item:29>,<customthings:item:47>],  [<customthings:item:50>,<customthings:item:21>,<customthings:item:50>,<customthings:item:21>,<customthings:item:50>,<customthings:item:21>,<customthings:item:50>,<customthings:item:21>,<customthings:item:50>],  [<customthings:item:21>,<customthings:item:50>,<customthings:item:21>,<customthings:item:50>,<customthings:item:21>,<customthings:item:50>,<customthings:item:21>,<customthings:item:50>,<customthings:item:21>],  [<customthings:item:21>,<customthings:item:50>,<customthings:item:21>,<customthings:item:50>,<customthings:item:21>,<customthings:item:50>,<customthings:item:21>,<customthings:item:50>,<customthings:item:21>],  [<customthings:item:50>,<customthings:item:21>,<customthings:item:50>,<customthings:item:21>,<customthings:item:50>,<customthings:item:21>,<customthings:item:50>,<customthings:item:21>,<customthings:item:50>],  [<customthings:item:47>,<customthings:item:29>,<customthings:item:29>,<customthings:item:29>,<customthings:item:29>,<customthings:item:29>,<customthings:item:29>,<customthings:item:29>,<customthings:item:47>],  [null,null,null,null,null,null,null,null,null],  [null,null,null,null,null,null,null,null,null]]);
mods.avaritia.ExtremeCrafting.addShaped(<Avaritia:Resource:5>, [[<eternalsingularity:eternal_singularity>,<Avaritia:big_pearl>,<Avaritia:Ultimate_Stew>,<Avaritia:Cosmic_Meatballs>,<Avaritia:Endest_Pearl>,<Avaritia:Resource:9>,<Avaritia:Resource_Block:0>,<Avaritia:Crystal_Matrix>,<ExtraUtilities:mini-soul:3>],  [<customthings:item:24>,<customthings:item:36>,<customthings:item:35>,<Botania:specialFlower>,<Botania:conjurationCatalyst>,<ae2wct:infinityBoosterCard>,<ChaosGod:Neo>,<ChaosGod:Logi1>,<RedstoneArsenal:material:128>],  [<ThaumicTinkerer:kamiResource>,<ThaumicTinkerer:kamiResource:1>,<ThaumicTinkerer:kamiResource:2>,<ThaumicTinkerer:kamiResource:4>,<ThaumicTinkerer:kamiResource:5>,<extracells:storage.component:3>,<extracells:storage.component:9>,<extracells:storage.component:17>,<appliedenergistics2:item.ItemMultiMaterial:38>],  [<ThaumicTinkerer:brightNitor>,<quantumflux:advancedCircuit>,<PneumaticCraft:advancedPCB>,<PneumaticCraft:pressureChamberWall>,<Botania:storage:1>,<Botania:manaResource:14>,<IC2:blockNuke>,<magicalcrops:essence_storage:5>,<magicalcrops:InfusionStoneMaster:0>],  [<MineFactoryReloaded:pinkslime:1>,<erebus:materials:65>,<simplyjetpacks:components:15>,<ExtraTiC:funStuffIngot>,<technom:itemBO:1>,<clayium:itemGems:809>,<WitchingGadgets:item.WG_Material:3>,<WitchingGadgets:item.WG_Material:4>,<WitchingGadgets:item.WG_Material:5>],  [<EnderIO:itemMaterial:9>,<ThermalExpansion:Frame:3>,<AWWayofTime:transcendentBloodOrb>,<AWWayofTime:armourForge>,<AWWayofTime:blockCrystal>,<appliedenergistics2:tile.BlockController>,<appliedenergistics2:item.ItemMultiMaterial:47>,<gregtech:gt.metaitem.01:32726>,<customthings:item:48>],  [<MineFactoryReloaded:upgrade.logic:2>,<gregtech:gt.blockmetal7:13>,<gregtech:gt.blockmetal5:2>,<gregtech:gt.metaitem.01:32677>,<gregtech:gt.metaitem.01:32657>,<gregtech:gt.metaitem.01:32647>,<gregtech:gt.metaitem.01:32638>,<gregtech:gt.metaitem.01:32622>,<gregtech:gt.metaitem.01:32608>],  [<gregtech:gt.metaitem.01:32697>,<ExtraUtilities:divisionSigil>,<DraconicEvolution:draconicCore>,<DraconicEvolution:wyvernCore>,<DraconicEvolution:awakenedCore>,<DraconicEvolution:chaoticCore>,<DraconicEvolution:chaosShard>,<DraconicEvolution:draconicBlock>,<ImmersiveEngineering:metal:20>],  [<Botania:dreamwood:0>,<PEEX:chaosmatterBlock>,<ae2stuff:Wireless>,<ForbiddenMagic:EldritchOrb>,<quantumflux:glowingMangalloy>,<TaintedMagic:ItemMaterial:3>,<ThermalExpansion:Tesseract>,<RedstoneArsenal:Storage>,<RedstoneArsenal:Storage:1>]]);
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Resource:5>);
mods.avaritia.ExtremeCrafting.addShaped(<customthings:item:50>, [[null,null,null,null,<DraconicEvolution:chaoticCore>,null,null,null,null],  [null,<DraconicEvolution:chaoticCore>,null,null,<Avaritia:Resource:4>,null,null,<DraconicEvolution:chaoticCore>,null],  [null,null,<Avaritia:Resource:4>,null,<Avaritia:Resource:5>,null,<Avaritia:Resource:4>,null,null],  [null,null,null,null,<Avaritia:Resource_Block>,null,null,null,null],  [<DraconicEvolution:chaoticCore>,<Avaritia:Resource:4>,<Avaritia:Resource:5>,<Avaritia:Resource_Block>,<ChaosGod:TheChaos>,<Avaritia:Resource_Block>,<Avaritia:Resource:5>,<Avaritia:Resource:4>,<DraconicEvolution:chaoticCore>],  [null,null,null,null,<Avaritia:Resource_Block>,null,null,null,null],  [null,null,<Avaritia:Resource:4>,null,<Avaritia:Resource:5>,null,<Avaritia:Resource:4>,null,null],  [null,<DraconicEvolution:chaoticCore>,null,null,<Avaritia:Resource:4>,null,null,<DraconicEvolution:chaoticCore>,null],  [null,null,null,null,<DraconicEvolution:chaoticCore>,null,null,null,null]]);
mods.avaritia.Compressor.add(<ChaosGod:Logi1>, 65892, <LogisticsPipes:item.PipeItemsBasicLogistics>);
mods.avaritia.Compressor.add(<ChaosGod:TheChaos>, 65192, <DraconicEvolution:chaosCrystal>);

mods.avaritia.ExtremeCrafting.addShaped(<ExtraUtilities:angelRing:1>, [[<ChaosGod:AngelWing>, <minecraft:gold_ingot>,null,null,null,null,null,<minecraft:gold_ingot>,<ChaosGod:AngelWing>],  [<ChaosGod:AngelWing>,<ChaosGod:AngelWing>,null,null,null,null,null,<ChaosGod:AngelWing>,<ChaosGod:AngelWing>],  [<minecraft:gold_ingot>,<ChaosGod:AngelWing>,<technom:itemMaterial>,<minecraft:gold_ingot>,<minecraft:gold_ingot>,<minecraft:gold_ingot>,<technom:itemMaterial>,<ChaosGod:AngelWing>,<minecraft:gold_ingot>],  [null,<technom:itemMaterial>,<minecraft:gold_ingot>,null,null,null,<minecraft:gold_ingot>,<technom:itemMaterial>,null],  [null,null,<minecraft:gold_ingot>,null,null,null,<minecraft:gold_ingot>,null,null],  [null,null,<minecraft:gold_ingot>,null,null,null,<minecraft:gold_ingot>,null,null],  [null,null,null,<minecraft:gold_ingot>,<minecraft:gold_ingot>,<minecraft:gold_ingot>,null,null,null],  [null,null,null,null,null,null,null,null,null],  [null,null,null,null,null,null,null,null,null]]);
mods.avaritia.Compressor.add(<ChaosGod:Infinity1>, 65893, <Avaritia:Resource_Block:1>);
mods.avaritia.Compressor.add(<ChaosGod:Neutoron>, 65893, <eternalsingularity:eternal_singularity>);

mods.avaritia.ExtremeCrafting.addShaped(<ProjectE:transmutation_table>, [[<customthings:block0:3>, <ProjectE:matter_block:1>, <ProjectE:matter_block:1>, <magicalcrops:UltimateFurnace>, <appliedenergistics2:item.ItemMultiPart:420>, <magicalcrops:UltimateFurnace>, <ProjectE:matter_block:1>, <ProjectE:matter_block:1>, <customthings:block0:3>],
																		[<ProjectE:matter_block:1>, <appliedenergistics2:item.ItemMultiMaterial:34>, <Avaritia:Resource:1>, <Avaritia:Resource:1>, <customthings:item:1>, <Avaritia:Resource:1>, <Avaritia:Resource:1>, <appliedenergistics2:item.ItemMultiMaterial:34>, <ProjectE:matter_block:1>],
																		[<ProjectE:matter_block:1>, <Avaritia:Resource:1>, <DraconicEvolution:draconicCore>, <ExtraPlanets:item.wafer:3>, <Botania:rune:12>, <ExtraPlanets:item.wafer:3>, <DraconicEvolution:draconicCore>, <Avaritia:Resource:1>, <ProjectE:matter_block:1>],
																		[<Botania:rune:9>, <customthings:block0>, <customthings:item:1>, <ExtraUtilities:unstableingot:2>, <Avaritia:Resource:5>, <ExtraUtilities:unstableingot:2>, <customthings:item:1>, <customthings:block0>, <Botania:rune:9>],
																		[<appliedenergistics2:item.ItemMultiPart:300>, null, <customthings:item:9>, <ProjectE:fuel_block:2>, <minecraft:bedrock>, <ProjectE:fuel_block:2>, <customthings:item:9>, null, <appliedenergistics2:item.ItemMultiPart:320>],
																		[<Botania:rune:15>, <customthings:block0>, <customthings:item:1>, <ExtraUtilities:unstableingot:2>, <Avaritia:Resource:5>, <ExtraUtilities:unstableingot:2>, <customthings:item:1>, <customthings:block0>, <Botania:rune:15>],
																		[<ProjectE:matter_block:1>, <Avaritia:Resource:1>, <DraconicEvolution:draconicCore>, <ExtraPlanets:item.wafer:3>, <Botania:rune:12>, <ExtraPlanets:item.wafer:3>, <DraconicEvolution:draconicCore>, <Avaritia:Resource:1>, <ProjectE:matter_block:1>],
																		[<ProjectE:matter_block:1>, <appliedenergistics2:item.ItemMultiMaterial:34>, <Avaritia:Resource:1>, <Avaritia:Resource:1>, <customthings:item:1>, <Avaritia:Resource:1>, <Avaritia:Resource:1>, <appliedenergistics2:item.ItemMultiMaterial:34>, <ProjectE:matter_block:1>],
																		[<customthings:block0:3>, <ProjectE:matter_block:1>, <ProjectE:matter_block:1>, <magicalcrops:UltimateFurnace>, <appliedenergistics2:tile.BlockController>, <magicalcrops:UltimateFurnace>, <ProjectE:matter_block:1>, <ProjectE:matter_block:1>, <customthings:block0:3>]]);

mods.avaritia.ExtremeCrafting.addShaped(<Magneticraft:infinite_energy>, [[<ThermalExpansion:Frame:3>, <ImmersiveEngineering:metalDevice:7>, <ImmersiveEngineering:metalDevice:7>, <ImmersiveEngineering:metalDevice:7>, <ImmersiveEngineering:metalDevice:7>, <ImmersiveEngineering:metalDevice:7>, <ImmersiveEngineering:metalDevice:7>, <ImmersiveEngineering:metalDevice:7>, <ThermalExpansion:Frame:3>],
																		[<ImmersiveEngineering:metalDevice:7>, <DraconicEvolution:draconiumEnergyCore:1>, <Mekanism:EnergyTablet>, <Mekanism:EnergyTablet>, <BigReactors:BRReactorPart:1>, <Mekanism:EnergyTablet>, <Mekanism:EnergyTablet>, <DraconicEvolution:draconiumEnergyCore:1>, <ImmersiveEngineering:metalDevice:7>],
																		[<ImmersiveEngineering:metalDevice:7>, <Mekanism:EnergyTablet>, <DraconicEvolution:draconiumEnergyCore:1>, <DraconicEvolution:draconiumEnergyCore:1>, <DraconicEvolution:reactorEnergyInjector>, <DraconicEvolution:draconiumEnergyCore:1>, <DraconicEvolution:draconiumEnergyCore:1>, <Mekanism:EnergyTablet>, <ImmersiveEngineering:metalDevice:7>],
																		[<ImmersiveEngineering:metalDevice:7>, <Mekanism:EnergyTablet>, <DraconicEvolution:draconiumEnergyCore:1>, <Avaritia:Resource:5>, <Mekanism:MachineBlock3>, <Avaritia:Resource:5>, <DraconicEvolution:draconiumEnergyCore:1>, <Mekanism:EnergyTablet>, <ImmersiveEngineering:metalDevice:7>],
																		[<ImmersiveEngineering:metalDevice:7>, <DraconicEvolution:reactorEnergyInjector>, null, <Mekanism:MachineBlock3>, <DraconicEvolution:chaoticCore>, <Mekanism:MachineBlock3>, null, <DraconicEvolution:reactorEnergyInjector>, <ImmersiveEngineering:metalDevice:7>],
																		[<ImmersiveEngineering:metalDevice:7>, <Mekanism:EnergyTablet>, <DraconicEvolution:draconiumEnergyCore:1>, <Avaritia:Resource:5>, <Mekanism:MachineBlock3>, <Avaritia:Resource:5>, <DraconicEvolution:draconiumEnergyCore:1>, <Mekanism:EnergyTablet>, <ImmersiveEngineering:metalDevice:7>],
																		[<ImmersiveEngineering:metalDevice:7>, <Mekanism:EnergyTablet>, <DraconicEvolution:draconiumEnergyCore:1>, <DraconicEvolution:draconiumEnergyCore:1>, null, <DraconicEvolution:draconiumEnergyCore:1>, <DraconicEvolution:draconiumEnergyCore:1>, <Mekanism:EnergyTablet>, <ImmersiveEngineering:metalDevice:7>],
																		[<ImmersiveEngineering:metalDevice:7>, <DraconicEvolution:draconiumEnergyCore:1>, <Mekanism:EnergyTablet>, <Mekanism:EnergyTablet>, <DraconicEvolution:reactorEnergyInjector>, <Mekanism:EnergyTablet>, <Mekanism:EnergyTablet>, <DraconicEvolution:draconiumEnergyCore:1>, <ImmersiveEngineering:metalDevice:7>],
																		[<ThermalExpansion:Frame:3>, <ImmersiveEngineering:metalDevice:7>, <ImmersiveEngineering:metalDevice:7>, <ImmersiveEngineering:metalDevice:7>, <ImmersiveEngineering:metalDevice:7>, <ImmersiveEngineering:metalDevice:7>, <ImmersiveEngineering:metalDevice:7>, <ImmersiveEngineering:metalDevice:7>, <ThermalExpansion:Frame:3>]]);

mods.avaritia.ExtremeCrafting.addShaped(<ProjectE:item.pe_tome>, [[null, null, null, null, null, null, null, null, null],
																				[null, null, null, null, null, null, null, null, null],
																				[null, null, <minecraft:enchanted_book>, <minecraft:enchanted_book>, <minecraft:enchanted_book>, <minecraft:enchanted_book>, <minecraft:enchanted_book>, null, null],
																				[null, null, <minecraft:enchanted_book>, <customthings:item:1>, <customthings:item:1>, <customthings:item:1>, <minecraft:enchanted_book>, null, null],
																				[null, null, <minecraft:enchanted_book>, <customthings:item:15>, <ProjectE:item.pe_transmutation_tablet>, <customthings:item:15>, <minecraft:enchanted_book>, null, null],
																				[null, null, <minecraft:enchanted_book>, <customthings:item:1>, <customthings:item:1>, <customthings:item:1>, <minecraft:enchanted_book>, null, null],
																				[null, null, <minecraft:enchanted_book>, <minecraft:enchanted_book>, <minecraft:enchanted_book>, <minecraft:enchanted_book>, <minecraft:enchanted_book>, null, null],
																				[null, null, null, null, null, null, null, null, null],
																				[null, null, null, null, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped(<Avaritia:Infinity_Pickaxe>, [[null, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, null],
																				[<Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <DraconicEvolution:draconicDistructionStaff>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource:6>],
																				[<Avaritia:Resource:6>, <Avaritia:Resource:6>, <RedstoneArsenal:tool.pickaxeFlux>, <quantumflux:eviscerator>, <GTFei:Plate5>, <Mekanism:AtomicDisassembler>, <EnderIO:item.darkSteel_pickaxe>, <Avaritia:Resource:6>, <Avaritia:Resource:6>],
																				[null, null, null, <ProjectE:item.pe_rm_morning_star>, <GTFei:Plate5>, <ProjectE:item.pe_rm_pick>, null, null, null],
																				[null, null, null, <ExtraUtilities:destructionpickaxe>, <GTFei:Plate5>, <Magneticraft:item.jack_hammer:*>, null, null, null],
																				[null, null, null, null, <GTFei:Plate5>, null, null, null, null],
																				[null, null, null, null, <GTFei:Plate5>, null, null, null, null],
																				[null, null, null, null, <GTFei:Plate5>, null, null, null, null],
																				[null, null, null, null, <DraconicEvolution:chaoticCore>, null, null, null, null]]);
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Infinity_Pickaxe>);

mods.avaritia.Compressor.add(<minecraft:iron_block>, 9, <ore:ingotIron>, true); 
mods.avaritia.Compressor.add(<minecraft:gold_block>, 9, <ore:ingotGold>, true); 
mods.avaritia.Compressor.add(<minecraft:emerald_block>, 9, <ore:gemEmerald>, true); 
mods.avaritia.Compressor.add(<ThermalFoundation:Storage>, 9, <ore:ingotCopper>, true); 
mods.avaritia.Compressor.add(<ThermalFoundation:Storage:1>, 9, <ore:ingotTin>, true); 
mods.avaritia.Compressor.add(<ThermalFoundation:Storage:2>, 9, <ore:ingotSilver>, true); 
mods.avaritia.Compressor.add(<ThermalFoundation:Storage:3>, 9, <ore:ingotLead>, true); 
mods.avaritia.Compressor.add(<ThermalFoundation:Storage:4>, 9, <ore:ingotNickel>, true); 
mods.avaritia.Compressor.add(<ThermalFoundation:Storage:5>, 9, <ore:ingotPlatinum>, true); 
mods.avaritia.Compressor.add(<ThermalFoundation:Storage:6>, 9, <ore:ingotMithril>, true); 
mods.avaritia.Compressor.add(<ThermalFoundation:Storage:7>, 9, <ore:ingotElectrum>, true); 
mods.avaritia.Compressor.add(<ThermalFoundation:Storage:8>, 9, <ore:ingotInvar>, true); 
mods.avaritia.Compressor.add(<ThermalFoundation:Storage:9>, 9, <ore:ingotBronze>, true); 
mods.avaritia.Compressor.add(<ThermalFoundation:Storage:10>, 9, <ore:ingotSignalum>, true); 
mods.avaritia.Compressor.add(<ThermalFoundation:Storage:11>, 9, <ore:ingotLumium>, true); 
mods.avaritia.Compressor.add(<ThermalFoundation:Storage:12>, 9, <ore:ingotEnderium>, true); 
mods.avaritia.Compressor.add(<TConstruct:MetalBlock>, 9, <ore:ingotCobalt>, true); 
mods.avaritia.Compressor.add(<TConstruct:MetalBlock:1>, 9, <ore:ingotArdite>, true); 
mods.avaritia.Compressor.add(<TConstruct:MetalBlock:2>, 9, <ore:ingotManyullyn>, true); 
mods.avaritia.Compressor.add(<TConstruct:MetalBlock:6>, 9, <ore:ingotAluminium>, true); 
mods.avaritia.Compressor.add(<TConstruct:MetalBlock:6>, 9, <ore:ingotAluminum>, true); 
mods.avaritia.Compressor.add(<TConstruct:MetalBlock:7>, 9, <ore:ingotAluminumBrass>, true); 
mods.avaritia.Compressor.add(<TConstruct:MetalBlock:7>, 9, <ore:ingotAluminiumBrass>, true); 
mods.avaritia.Compressor.add(<TConstruct:MetalBlock:8>, 9, <ore:ingotAlumite>, true); 
mods.avaritia.Compressor.add(<TConstruct:MetalBlock:9>, 9, <ore:ingotSteel>, true); 
mods.avaritia.Compressor.add(<Magneticraft:block_tungsten>, 9, <ore:ingotTungsten>, true); 
mods.avaritia.Compressor.add(<Magneticraft:block_brass>, 9, <ore:ingotBrass>, true); 
mods.avaritia.Compressor.add(<Magneticraft:block_zinc>, 9, <ore:ingotZinc>, true); 
mods.avaritia.Compressor.add(<GalacticraftMars:tile.mars:8>, 9, <ore:ingotDesh>, true); 
mods.avaritia.Compressor.add(<BigReactors:BRMetalBlock>, 9, <ore:ingotYellorium>, true); 
mods.avaritia.Compressor.add(<ImmersiveEngineering:storage:5>, 9, <ore:ingotConstantan>, true); 
mods.avaritia.Compressor.add(<ImmersiveEngineering:storage:5>, 9, <ore:ingotCupronickel>, true);

mods.avaritia.ExtremeCrafting.addShaped(<ThermalExpansion:Tank>, [[<ThermalExpansion:Cell>, <ExtraUtilities:drum:1>, <ExtraUtilities:drum:1>, <ExtraUtilities:drum:1>, <ExtraUtilities:drum:1>, <ExtraUtilities:drum:1>, <ExtraUtilities:drum:1>, <ExtraUtilities:drum:1>, <ThermalExpansion:Cell>], [<ExtraUtilities:drum:1>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <ExtraUtilities:drum:1>], [<ExtraUtilities:drum:1>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <ExtraUtilities:drum:1>], [<ExtraUtilities:drum:1>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <ExtraUtilities:drum:1>], [<ExtraUtilities:drum:1>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <ExtraUtilities:drum:1>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <ExtraUtilities:drum:1>], [<ExtraUtilities:drum:1>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <ExtraUtilities:drum:1>], [<ExtraUtilities:drum:1>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <ExtraUtilities:drum:1>], [<ExtraUtilities:drum:1>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <GTFei:Plate5>, <ExtraUtilities:drum:1>], [<ThermalExpansion:Cell>, <ExtraUtilities:drum:1>, <ExtraUtilities:drum:1>, <ExtraUtilities:drum:1>, <ExtraUtilities:drum:1>, <ExtraUtilities:drum:1>, <ExtraUtilities:drum:1>, <ExtraUtilities:drum:1>, <ThermalExpansion:Cell>]]);

mods.avaritia.ExtremeCrafting.addShaped(<ThermalExpansion:capacitor>, [[<ThermalFoundation:Storage:11>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <ThermalFoundation:Storage:11>], [<gregtech:gt.blockmetal4:4>, <IC2:itemRTGPellet>, <ThermalExpansion:Frame:9>, <ThermalExpansion:Frame:9>, <IC2:itemRTGPellet>, <ThermalExpansion:Frame:9>, <ThermalExpansion:Frame:9>, <IC2:itemRTGPellet>, <gregtech:gt.blockmetal4:4>], [<gregtech:gt.blockmetal4:4>, <ThermalExpansion:Frame:9>, <DraconicEvolution:draconiumFluxCapacitor>, <DraconicEvolution:draconiumFluxCapacitor>, <DraconicEvolution:draconiumFluxCapacitor>, <DraconicEvolution:draconiumFluxCapacitor>, <DraconicEvolution:draconiumFluxCapacitor>, <ThermalExpansion:Frame:9>, <gregtech:gt.blockmetal4:4>], [<gregtech:gt.blockmetal4:4>, <ThermalExpansion:Frame:9>, <DraconicEvolution:draconiumFluxCapacitor>, <AdvancedSolarPanel:BlockAdvSolarPanel:2>, <AdvancedSolarPanel:BlockAdvSolarPanel:2>, <AdvancedSolarPanel:BlockAdvSolarPanel:2>, <DraconicEvolution:draconiumFluxCapacitor>, <ThermalExpansion:Frame:9>, <gregtech:gt.blockmetal4:4>], [<gregtech:gt.blockmetal4:4>, <IC2:itemRTGPellet>, <DraconicEvolution:draconiumFluxCapacitor>, <AdvancedSolarPanel:BlockAdvSolarPanel:2>, <AdvancedSolarPanel:BlockAdvSolarPanel:2>, <AdvancedSolarPanel:BlockAdvSolarPanel:2>, <DraconicEvolution:draconiumFluxCapacitor>, <IC2:itemRTGPellet>, <gregtech:gt.blockmetal4:4>], [<gregtech:gt.blockmetal4:4>, <ThermalExpansion:Frame:9>, <DraconicEvolution:draconiumFluxCapacitor>, <AdvancedSolarPanel:BlockAdvSolarPanel:2>, <AdvancedSolarPanel:BlockAdvSolarPanel:2>, <AdvancedSolarPanel:BlockAdvSolarPanel:2>, <DraconicEvolution:draconiumFluxCapacitor>, <ThermalExpansion:Frame:9>, <gregtech:gt.blockmetal4:4>], [<gregtech:gt.blockmetal4:4>, <ThermalExpansion:Frame:9>, <DraconicEvolution:draconiumFluxCapacitor>, <DraconicEvolution:draconiumFluxCapacitor>, <DraconicEvolution:draconiumFluxCapacitor>, <DraconicEvolution:draconiumFluxCapacitor>, <DraconicEvolution:draconiumFluxCapacitor>, <ThermalExpansion:Frame:9>, <gregtech:gt.blockmetal4:4>], [<gregtech:gt.blockmetal4:4>, <IC2:itemRTGPellet>, <ThermalExpansion:Frame:9>, <ThermalExpansion:Frame:9>, <IC2:itemRTGPellet>, <ThermalExpansion:Frame:9>, <ThermalExpansion:Frame:9>, <IC2:itemRTGPellet>, <gregtech:gt.blockmetal4:4>], [<ThermalFoundation:Storage:11>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <ThermalFoundation:Storage:11>]]);


mods.avaritia.ExtremeCrafting.remove(<ThermalExpansion:Cell>);
mods.avaritia.ExtremeCrafting.addShaped(<ThermalExpansion:Cell>, [[<ThermalFoundation:Storage:11>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <ThermalFoundation:Storage:11>], [<gregtech:gt.blockmetal4:4>, <IC2:itemRTGPellet>, <ThermalExpansion:Frame:9>, <ThermalExpansion:Frame:9>, <IC2:itemRTGPellet>, <ThermalExpansion:Frame:9>, <ThermalExpansion:Frame:9>, <IC2:itemRTGPellet>, <gregtech:gt.blockmetal4:4>], [<gregtech:gt.blockmetal4:4>, <ThermalExpansion:Frame:9>, <DraconicEvolution:draconiumFluxCapacitor:1>, <DraconicEvolution:draconiumFluxCapacitor:1>, <DraconicEvolution:draconiumFluxCapacitor:1>, <DraconicEvolution:draconiumFluxCapacitor:1>, <DraconicEvolution:draconiumFluxCapacitor:1>, <ThermalExpansion:Frame:9>, <gregtech:gt.blockmetal4:4>], [<gregtech:gt.blockmetal4:4>, <ThermalExpansion:Frame:9>, <DraconicEvolution:draconiumFluxCapacitor:1>, <AdvancedSolarPanel:BlockAdvSolarPanel:3>, <AdvancedSolarPanel:BlockAdvSolarPanel:3>, <AdvancedSolarPanel:BlockAdvSolarPanel:3>, <DraconicEvolution:draconiumFluxCapacitor:1>, <ThermalExpansion:Frame:9>, <gregtech:gt.blockmetal4:4>], [<gregtech:gt.blockmetal4:4>, <IC2:itemRTGPellet>, <DraconicEvolution:draconiumFluxCapacitor:1>, <AdvancedSolarPanel:BlockAdvSolarPanel:3>, <AdvancedSolarPanel:BlockAdvSolarPanel:3>, <AdvancedSolarPanel:BlockAdvSolarPanel:3>, <DraconicEvolution:draconiumFluxCapacitor:1>, <IC2:itemRTGPellet>, <gregtech:gt.blockmetal4:4>], [<gregtech:gt.blockmetal4:4>, <ThermalExpansion:Frame:9>, <DraconicEvolution:draconiumFluxCapacitor:1>, <AdvancedSolarPanel:BlockAdvSolarPanel:3>, <AdvancedSolarPanel:BlockAdvSolarPanel:3>, <AdvancedSolarPanel:BlockAdvSolarPanel:3>, <DraconicEvolution:draconiumFluxCapacitor:1>, <ThermalExpansion:Frame:9>, <gregtech:gt.blockmetal4:4>], [<gregtech:gt.blockmetal4:4>, <ThermalExpansion:Frame:9>, <DraconicEvolution:draconiumFluxCapacitor:1>, <DraconicEvolution:draconiumFluxCapacitor:1>, <DraconicEvolution:draconiumFluxCapacitor:1>, <DraconicEvolution:draconiumFluxCapacitor:1>, <DraconicEvolution:draconiumFluxCapacitor:1>, <ThermalExpansion:Frame:9>, <gregtech:gt.blockmetal4:4>], [<gregtech:gt.blockmetal4:4>, <IC2:itemRTGPellet>, <ThermalExpansion:Frame:9>, <ThermalExpansion:Frame:9>, <IC2:itemRTGPellet>, <ThermalExpansion:Frame:9>, <ThermalExpansion:Frame:9>, <IC2:itemRTGPellet>, <gregtech:gt.blockmetal4:4>], [<ThermalFoundation:Storage:11>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <gregtech:gt.blockmetal4:4>, <ThermalFoundation:Storage:11>]]);

mods.avaritia.ExtremeCrafting.remove(<appliedenergistics2:tile.BlockCreativeEnergyCell>);

mods.avaritia.ExtremeCrafting.addShaped(<appliedenergistics2:tile.BlockCreativeEnergyCell>, [[<ExtraPlanets:item.wafer:3>, <Avaritia:Resource:6>, <Mekanism:BasicBlock:4>, <Mekanism:BasicBlock:4>, <ExtraPlanets:item.wafer:3>, <Mekanism:BasicBlock:4>, <Mekanism:BasicBlock:4>, <Avaritia:Resource:6>, <ExtraPlanets:item.wafer:3>],
																							[<Avaritia:Resource:6>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <SolarFlux:solar12>, <SolarFlux:solar12>, <Magneticraft:infinite_energy>, <SolarFlux:solar12>, <SolarFlux:solar12>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <Avaritia:Resource:6>],
																							[<Avaritia:Resource:6>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <appliedenergistics2:tile.BlockInterface>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <Avaritia:Resource:6>],
																							[<Avaritia:Resource_Block:1>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <Magneticraft:infinite_energy>, <ThermalDynamics:ThermalDynamics_0:6>, <Magneticraft:infinite_energy>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <Avaritia:Resource_Block:1>],
																							[<ExtraPlanets:item.wafer:5>, <Avaritia:Singularity:3>, <Avaritia:Singularity:3>, <Avaritia:Singularity:3>, <appliedenergistics2:tile.BlockController>, <Avaritia:Singularity:3>, <Avaritia:Singularity:3>, <Avaritia:Singularity:3>, <ExtraPlanets:item.wafer:5>],
																							[<Avaritia:Resource_Block:1>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <Magneticraft:infinite_energy>, <Avaritia:Singularity:3>, <Magneticraft:infinite_energy>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <Avaritia:Resource_Block:1>],
																							[<Avaritia:Resource:6>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <Avaritia:Singularity:3>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <Avaritia:Resource:6>],
																							[<Avaritia:Resource:6>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <Avaritia:Singularity:3>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <Avaritia:Resource:6>],
																							[<ExtraPlanets:item.wafer:4>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <Avaritia:Resource_Block:1>, <ExtraPlanets:item.wafer:4>, <Avaritia:Resource_Block:1>, <Avaritia:Resource:6>, <Avaritia:Resource:6>, <ExtraPlanets:item.wafer:4>]]);

mods.avaritia.ExtremeCrafting.addShaped(<PneumaticCraft:creativeCompressor>, [[<customthings:item:54>, <PneumaticCraft:plastic>, <PneumaticCraft:plastic>, <PneumaticCraft:plastic>, <PneumaticCraft:compressedIronBlock>, <PneumaticCraft:plastic>, <PneumaticCraft:plastic>, <PneumaticCraft:plastic>, <customthings:item:54>],
																				[<aobd:crystalCrystal>, <PneumaticCraft:transistor>, <PneumaticCraft:transistor>, <PneumaticCraft:advancedPCB>, <PneumaticCraft:advancedPCB>, <PneumaticCraft:advancedPCB>, <PneumaticCraft:transistor>, <PneumaticCraft:transistor>, <aobd:crystalCrystal>],
																				[<aobd:crystalCrystal>, <PneumaticCraft:transistor>, <PneumaticCraft:advancedAirCompressor>, <PneumaticCraft:advancedPCB>, <PneumaticCraft:advancedPCB>, <PneumaticCraft:advancedPCB>, <PneumaticCraft:advancedAirCompressor>, <PneumaticCraft:transistor>, <aobd:crystalCrystal>],
																				[<aobd:crystalCrystal>, <PneumaticCraft:transistor>, <PneumaticCraft:advancedAirCompressor>, <extracells:storage.component:17>, <extracells:storage.component:17>, <extracells:storage.component:17>, <PneumaticCraft:advancedAirCompressor>, <PneumaticCraft:transistor>, <aobd:crystalCrystal>],
																				[<PneumaticCraft:compressedIronBlock>, <PneumaticCraft:transistor>, <PneumaticCraft:advancedAirCompressor>, <extracells:storage.component:17>, <ThermalExpansion:Tank>, <extracells:storage.component:17>, <PneumaticCraft:advancedAirCompressor>, <PneumaticCraft:transistor>, <PneumaticCraft:compressedIronBlock>],
																				[<aobd:crystalCrystal>, <PneumaticCraft:transistor>, <PneumaticCraft:advancedAirCompressor>, <extracells:storage.component:17>, <extracells:storage.component:17>, <extracells:storage.component:17>, <PneumaticCraft:advancedAirCompressor>, <PneumaticCraft:transistor>, <aobd:crystalCrystal>],
																				[<aobd:crystalCrystal>, <PneumaticCraft:transistor>, <PneumaticCraft:advancedAirCompressor>, <PneumaticCraft:advancedPCB>, <PneumaticCraft:advancedPCB>, <PneumaticCraft:advancedPCB>, <PneumaticCraft:advancedAirCompressor>, <PneumaticCraft:transistor>, <aobd:crystalCrystal>],
																				[<aobd:crystalCrystal>, <PneumaticCraft:transistor>, <PneumaticCraft:transistor>, <PneumaticCraft:advancedPCB>, <PneumaticCraft:advancedPCB>, <PneumaticCraft:advancedPCB>, <PneumaticCraft:transistor>, <PneumaticCraft:transistor>, <aobd:crystalCrystal>],
																				[<customthings:item:54>, <PneumaticCraft:plastic>, <PneumaticCraft:plastic>, <PneumaticCraft:plastic>, <PneumaticCraft:compressedIronBlock>, <PneumaticCraft:plastic>, <PneumaticCraft:plastic>, <PneumaticCraft:plastic>, <customthings:item:54>]]);

mods.avaritia.ExtremeCrafting.addShaped(<BigReactors:BRMultiblockCreativePart:1>, [[<PneumaticCraft:transistor>, <PneumaticCraft:transistor>, <PneumaticCraft:transistor>, <PneumaticCraft:transistor>, <Magneticraft:infinite_steam>, <PneumaticCraft:transistor>, <PneumaticCraft:transistor>, <PneumaticCraft:transistor>, <PneumaticCraft:transistor>],
																				[<PneumaticCraft:transistor>, <BigReactors:BRTurbinePart>, <BigReactors:BRTurbinePart>, <BigReactors:BRTurbinePart>, <BigReactors:BRTurbinePart>, <BigReactors:BRTurbinePart>, <BigReactors:BRTurbinePart>, <BigReactors:BRTurbinePart>, <PneumaticCraft:transistor>],
																				[<PneumaticCraft:transistor>, <BigReactors:BRTurbinePart>, <BigReactors:BRMetalBlock:4>, <BigReactors:BRMetalBlock:4>, <BigReactors:BRMetalBlock:4>, <BigReactors:BRMetalBlock:4>, <BigReactors:BRMetalBlock:4>, <BigReactors:BRTurbinePart>, <PneumaticCraft:transistor>],
																				[<PneumaticCraft:transistor>, <PneumaticCraft:airCanister:*>, <PneumaticCraft:airCanister:*>, <customthings:item:54>, <customthings:item:54>, <customthings:item:54>, <PneumaticCraft:airCanister:*>, <PneumaticCraft:airCanister:*>, <PneumaticCraft:transistor>],
																				[<Magneticraft:infinite_steam>, <PneumaticCraft:printedCircuitBoard>, <PneumaticCraft:printedCircuitBoard>, <customthings:item:36>, <customthings:item:36>, <customthings:item:36>, <PneumaticCraft:printedCircuitBoard>, <PneumaticCraft:printedCircuitBoard>, <Magneticraft:infinite_steam>],
																				[<PneumaticCraft:transistor>, <PneumaticCraft:airCanister:*>, <PneumaticCraft:airCanister:*>, <customthings:item:54>, <customthings:item:54>, <customthings:item:54>, <PneumaticCraft:airCanister:*>, <PneumaticCraft:airCanister:*>, <PneumaticCraft:transistor>],
																				[<PneumaticCraft:transistor>, <BigReactors:BRTurbinePart>, <BigReactors:BRMetalBlock:4>, <BigReactors:BRMetalBlock:4>, <BigReactors:BRMetalBlock:4>, <BigReactors:BRMetalBlock:4>, <BigReactors:BRMetalBlock:4>, <BigReactors:BRTurbinePart>, <PneumaticCraft:transistor>],
																				[<PneumaticCraft:transistor>, <BigReactors:BRTurbinePart>, <BigReactors:BRTurbinePart>, <BigReactors:BRTurbinePart>, <BigReactors:BRTurbinePart>, <BigReactors:BRTurbinePart>, <BigReactors:BRTurbinePart>, <BigReactors:BRTurbinePart>, <PneumaticCraft:transistor>],
																				[<PneumaticCraft:transistor>, <PneumaticCraft:transistor>, <PneumaticCraft:transistor>, <PneumaticCraft:transistor>, <Magneticraft:infinite_steam>, <PneumaticCraft:transistor>, <PneumaticCraft:transistor>, <PneumaticCraft:transistor>, <PneumaticCraft:transistor>]]);

mods.avaritia.ExtremeCrafting.addShaped(<DraconicEvolution:draconicDistructionStaff>, [[null, <DraconicEvolution:draconicIngot>, <DraconicEvolution:draconicIngot>, <DraconicEvolution:draconicIngot>, <DraconicEvolution:awakenedCore>, <DraconicEvolution:draconicIngot>, <DraconicEvolution:draconicIngot>, <DraconicEvolution:draconicIngot>, null],
																				[<DraconicEvolution:draconicIngot>, <DraconicEvolution:draconicIngot>, <DraconicEvolution:draconicPickaxe>, <DraconicEvolution:draconicIngot>, <DraconicEvolution:draconicShovel>, <DraconicEvolution:draconicIngot>, <DraconicEvolution:draconicSword>, <DraconicEvolution:draconicIngot>, <DraconicEvolution:draconicIngot>],
																				[<DraconicEvolution:draconicIngot>, null, <DraconicEvolution:draconicIngot>, <DraconicEvolution:draconicIngot>, <DraconicEvolution:awakenedCore>, <DraconicEvolution:draconicIngot>, <DraconicEvolution:draconicIngot>, null, <DraconicEvolution:draconicIngot>],
																				[null, null, null, <DraconicEvolution:draconicIngot>, <customthings:item:6>, <DraconicEvolution:draconicIngot>, null, null, null],
																				[null, null, null, <DraconicEvolution:draconicIngot>, <DraconicEvolution:awakenedCore>, <DraconicEvolution:draconicIngot>, null, null, null],
																				[null, null, null, <DraconicEvolution:draconicIngot>, <customthings:item:6>, <DraconicEvolution:draconicIngot>, null, null, null],
																				[null, null, null, <DraconicEvolution:draconicIngot>, <DraconicEvolution:awakenedCore>, <DraconicEvolution:draconicIngot>, null, null, null],
																				[null, null, null, <DraconicEvolution:draconicIngot>, <customthings:item:6>, <DraconicEvolution:draconicIngot>, null, null, null],
																				[null, null, null, <DraconicEvolution:draconicIngot>, <DraconicEvolution:draconiumEnergyCore:1>, <DraconicEvolution:draconicIngot>, null, null, null]]);

mods.avaritia.ExtremeCrafting.remove(<Avaritia:Neutronium_Compressor>);

mods.avaritia.ExtremeCrafting.addShaped(<Avaritia:Neutronium_Compressor>, [[<Avaritia:Resource:1>, <Translocator:translocator>, <Translocator:translocator>, <Translocator:translocator>, <Translocator:translocator>, <Translocator:translocator>, <Translocator:translocator>, <Translocator:translocator>, <Avaritia:Resource:1>],
																			[<ExtraPlanets:tier10Items:4>, null, <TConstruct:heavyPlate:500>, null, null, null, <TConstruct:heavyPlate:500>, null, <ExtraPlanets:tier10Items:4>],
																			[<Avaritia:Resource:1>, null, <TConstruct:heavyPlate:500>, null, null, null, <TConstruct:heavyPlate:500>, null, <Avaritia:Resource:1>],
																			[<ExtraPlanets:tier10Items:4>, null, <TConstruct:heavyPlate:500>, null, null, null, <TConstruct:heavyPlate:500>, null, <ExtraPlanets:tier10Items:4>],
																			[<RedstoneArsenal:Storage:1>, <TConstruct:toughRod:500>, <TConstruct:heavyPlate:500>, null, <Avaritia:Resource_Block>, null, <TConstruct:heavyPlate:500>, <TConstruct:toughRod:500>, <RedstoneArsenal:Storage:1>],
																			[<ExtraPlanets:tier10Items:4>, null, <TConstruct:heavyPlate:500>, null, null, null, <TConstruct:heavyPlate:500>, null, <ExtraPlanets:tier10Items:4>],
																			[<Avaritia:Resource:1>, null, <TConstruct:heavyPlate:500>, null, null, null, <TConstruct:heavyPlate:500>, null, <Avaritia:Resource:1>],
																			[<ExtraPlanets:tier10Items:4>, null, <TConstruct:heavyPlate:500>, null, null, null, <TConstruct:heavyPlate:500>, null, <ExtraPlanets:tier10Items:4>],
																			[<Avaritia:Resource:1>, <ExtraPlanets:tier10Items:4>, <Avaritia:Resource:1>, <ExtraPlanets:tier10Items:4>, <Avaritia:Resource:1>, <ExtraPlanets:tier10Items:4>, <Avaritia:Resource:1>, <ExtraPlanets:tier10Items:4>, <Avaritia:Resource:1>]]);

mods.avaritia.ExtremeCrafting.addShaped(<eternalsingularity:combined_singularity>, [
[null, null, null, null, null, null, null, null, null],
[null, null, <ore:blockPlutonium>, <ore:blockPlutonium>, null, null, <ore:blockPlutonium>, null, null],
[null, <ore:blockPlutonium>, null, null, <Avaritia:Singularity:2>, null, null, <ore:blockPlutonium>, null],
[null, null, null, <Avaritia:Singularity:1>, <ExtraUtilities:block_bedrockium>, <Avaritia:Singularity:8>, null, <ore:blockPlutonium>, null],
[null, null, <Avaritia:Singularity>, <ExtraUtilities:block_bedrockium>, <Avaritia:Singularity:3>, <ExtraUtilities:block_bedrockium>, <Avaritia:Singularity:6>, null, null],
[null, <ore:blockPlutonium>, null, <Avaritia:Singularity:7>, <ExtraUtilities:block_bedrockium>, <Avaritia:Singularity:5>, null, null, null],
[null, <ore:blockPlutonium>, null, null, <Avaritia:Singularity:4>, null, null, <ore:blockPlutonium>, null],
[null, null, <ore:blockPlutonium>, null, null, <ore:blockPlutonium>, <ore:blockPlutonium>, null, null],
[null, null, null, null, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped(<eternalsingularity:combined_singularity:1>, [
[null, null, null, null, null, null, null, null, null],
[null, null, <ore:blockPlutonium>, <ore:blockPlutonium>, null, null, <ore:blockPlutonium>, null, null],
[null, <ore:blockPlutonium>, null, null, <Avaritia:Singularity:9>, null, null, <ore:blockPlutonium>, null],
[null, null, null, <Avaritia:Singularity:10>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.vanilla.singularity>, null, <ore:blockPlutonium>, null],
[null, null, <universalsingularities:universal.vanilla.singularity:2>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.vanilla.singularity:1>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.general.singularity:3>, null, null],
[null, <ore:blockPlutonium>, null, <universalsingularities:universal.general.singularity>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.general.singularity:1>, null, null, null],
[null, <ore:blockPlutonium>, null, null, <universalsingularities:universal.general.singularity:2>, null, null, <ore:blockPlutonium>, null],
[null, null, <ore:blockPlutonium>, null, null, <ore:blockPlutonium>, <ore:blockPlutonium>, null, null],
[null, null, null, null, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped(<eternalsingularity:combined_singularity:2>, [
[null, null, null, null, null, null, null, null, null],
[null, null, <ore:blockPlutonium>, <ore:blockPlutonium>, null, null, <ore:blockPlutonium>, null, null],
[null, <ore:blockPlutonium>, null, null, <universalsingularities:universal.general.singularity:4>, null, null, <ore:blockPlutonium>, null],
[null, null, null, <universalsingularities:universal.general.singularity:5>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.general.singularity:6>, null, <ore:blockPlutonium>, null],
[null, null, <universalsingularities:universal.general.singularity:7>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.general.singularity:8>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.general.singularity:9>, null, null],
[null, <ore:blockPlutonium>, null, <universalsingularities:universal.general.singularity:10>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.general.singularity:11>, null, null, null],
[null, <ore:blockPlutonium>, null, null, <universalsingularities:universal.general.singularity:12>, null, null, <ore:blockPlutonium>, null],
[null, null, <ore:blockPlutonium>, null, null, <ore:blockPlutonium>, <ore:blockPlutonium>, null, null],
[null, null, null, null, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped(<eternalsingularity:combined_singularity:3>, [
[null, null, null, null, null, null, null, null, null],
[null, null, <ore:blockPlutonium>, <ore:blockPlutonium>, null, null, <ore:blockPlutonium>, null, null],
[null, <ore:blockPlutonium>, null, null, <universalsingularities:universal.general.singularity:13>, null, null, <ore:blockPlutonium>, null],
[null, null, null, <universalsingularities:universal.general.singularity:14>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.general.singularity:15>, null, <ore:blockPlutonium>, null],
[null, null, <universalsingularities:universal.general.singularity:16>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.general.singularity:17>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.general.singularity:18>, null, null],
[null, <ore:blockPlutonium>, null, <universalsingularities:universal.general.singularity:19>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.general.singularity:20>, null, null, null],
[null, <ore:blockPlutonium>, null, null, <universalsingularities:universal.general.singularity:21>, null, null, <ore:blockPlutonium>, null],
[null, null, <ore:blockPlutonium>, null, null, <ore:blockPlutonium>, <ore:blockPlutonium>, null, null],
[null, null, null, null, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped(<eternalsingularity:combined_singularity:4>, [
[null, null, null, null, null, null, null, null, null],
[null, null, <ore:blockPlutonium>, <ore:blockPlutonium>, null, null, <ore:blockPlutonium>, null, null],
[null, <ore:blockPlutonium>, null, null, <universalsingularities:universal.general.singularity:22>, null, null, <ore:blockPlutonium>, null],
[null, null, null, <universalsingularities:universal.general.singularity:23>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.general.singularity:24>, null, <ore:blockPlutonium>, null],
[null, null, <universalsingularities:universal.general.singularity:25>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.general.singularity:26>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.general.singularity:27>, null, null],
[null, <ore:blockPlutonium>, null, <universalsingularities:universal.general.singularity:28>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.general.singularity:29>, null, null, null],
[null, <ore:blockPlutonium>, null, null, <universalsingularities:universal.general.singularity:30>, null, null, <ore:blockPlutonium>, null],
[null, null, <ore:blockPlutonium>, null, null, <ore:blockPlutonium>, <ore:blockPlutonium>, null, null],
[null, null, null, null, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped(<eternalsingularity:combined_singularity:5>, [
[null, null, null, null, null, null, null, null, null],
[null, null, <ore:blockPlutonium>, <ore:blockPlutonium>, null, null, <ore:blockPlutonium>, null, null],
[null, <ore:blockPlutonium>, null, null, <universalsingularities:universal.draconicEvolution.singularity>, null, null, <ore:blockPlutonium>, null],
[null, null, null, <universalsingularities:universal.draconicEvolution.singularity:1>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.enderIO.singularity>, null, <ore:blockPlutonium>, null],
[null, null, <universalsingularities:universal.enderIO.singularity:1>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.enderIO.singularity:2>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.enderIO.singularity:3>, null, null],
[null, <ore:blockPlutonium>, null, <universalsingularities:universal.enderIO.singularity:4>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.enderIO.singularity:5>, null, null, null],
[null, <ore:blockPlutonium>, null, null, <universalsingularities:universal.enderIO.singularity:6>, null, null, <ore:blockPlutonium>, null],
[null, null, <ore:blockPlutonium>, null, null, <ore:blockPlutonium>, <ore:blockPlutonium>, null, null],
[null, null, null, null, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped(<eternalsingularity:combined_singularity:6>, [
[null, null, null, null, null, null, null, null, null],
[null, null, <ore:blockPlutonium>, <ore:blockPlutonium>, null, null, <ore:blockPlutonium>, null, null],
[null, <ore:blockPlutonium>, null, null, <universalsingularities:universal.enderIO.singularity:7>, null, null, <ore:blockPlutonium>, null],
[null, null, null, <universalsingularities:universal.extraUtilities.singularity>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.projectRed.singularity>, null, <ore:blockPlutonium>, null],
[null, null, <universalsingularities:universal.tinkersConstruct.singularity>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.tinkersConstruct.singularity:1>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.tinkersConstruct.singularity:2>, null, null],
[null, <ore:blockPlutonium>, null, <universalsingularities:universal.tinkersConstruct.singularity:3>, <ExtraUtilities:block_bedrockium>, <universalsingularities:universal.tinkersConstruct.singularity:4>, null, null, null],
[null, <ore:blockPlutonium>, null, null, <universalsingularities:universal.tinkersConstruct.singularity:6>, null, null, <ore:blockPlutonium>, null],
[null, null, <ore:blockPlutonium>, null, null, <ore:blockPlutonium>, <ore:blockPlutonium>, null, null],
[null, null, null, null, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped(<eternalsingularity:eternal_singularity>, [
[null, null, null, null, null, <Avaritia:Resource_Block>, null, null, null],
[null, null, <ore:blockPlutonium>, <ore:blockPlutonium>, null, null, <ore:blockPlutonium>, null, null],
[null, <ore:blockPlutonium>, null, null, <eternalsingularity:combined_singularity>, null, null, <ore:blockPlutonium>, null],
[<Avaritia:Resource_Block>, null, null, <eternalsingularity:combined_singularity:1>, <Avaritia:Resource_Block>, <eternalsingularity:combined_singularity:2>, null, <ore:blockPlutonium>, null],
[null, null, <Avaritia:Resource_Block>, <Avaritia:Resource_Block>, <eternalsingularity:combined_singularity:3>, <Avaritia:Resource_Block>, <Avaritia:Resource_Block>, null, null],
[null, <ore:blockPlutonium>, null, <eternalsingularity:combined_singularity:4>, <Avaritia:Resource_Block>, <eternalsingularity:combined_singularity:5>, null, null, <Avaritia:Resource_Block>],
[null, <ore:blockPlutonium>, null, null, <eternalsingularity:combined_singularity:6>, null, null, <ore:blockPlutonium>, null],
[null, null, <ore:blockPlutonium>, null, null, <ore:blockPlutonium>, <ore:blockPlutonium>, null, null],
[null, null, null, <Avaritia:Resource_Block>, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.remove(<eternalsingularity:eternal_singularity>);

mods.avaritia.ExtremeCrafting.addShaped(<Avaritia:Orb_Armok>, [
[null, null, null, <ore:plateInfinity>, <ore:plateInfinity>, <ore:plateInfinity>, null, null, null],
[null, null, <ore:plateInfinity>, <ForbiddenMagic:EldritchOrb>, <ore:plateInfinity>, <ForbiddenMagic:EldritchOrb>, <ore:plateInfinity>, null, null],
[null, null, <ore:plateInfinity>, <ore:plateInfinity>, <ore:plateCosmicNeutronium>, <ore:plateInfinity>, <ore:plateInfinity>, null, null],
[null, <ore:plateCosmicNeutronium>, <ore:plateInfinity>, <ForbiddenMagic:EldritchOrb>, <ore:plateInfinity>, <ForbiddenMagic:EldritchOrb>, <ore:plateInfinity>, <ore:plateCosmicNeutronium>, null],
[<ore:plateCosmicNeutronium>, <ore:plateCosmicNeutronium>, <ore:plateCosmicNeutronium>, <ore:plateInfinity>, <Avaritia:Resource:5>, <ore:plateInfinity>, <ore:plateCosmicNeutronium>, <ore:plateCosmicNeutronium>, <ore:plateCosmicNeutronium>],
[null, <ore:plateCosmicNeutronium>, <ore:plateCosmicNeutronium>, <ore:plateCosmicNeutronium>, <TConstruct:heavyPlate:500>, <ore:plateCosmicNeutronium>, <ore:plateCosmicNeutronium>, <ore:plateCosmicNeutronium>, null],
[null, null, null, <ore:plateCosmicNeutronium>, <ore:plateCosmicNeutronium>, <ore:plateCosmicNeutronium>, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped(<DraconicEvolution:teleporterStand>, [
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, <ore:slabStone>, <ore:stickBlaze>, DCham, <ore:stickBlaze>, <ore:slabStone>, null, null],
[null, null, null, <ore:slabStone>, <ore:slabStone>, <ore:slabStone>, null, null, null],
[null, null, null, null, <DraconicEvolution:infusedObsidian>, null, null, null, null],
[null, null, null, null, <DraconicEvolution:infusedObsidian>, null, null, null, null],
[null, null, null, null, <DraconicEvolution:infusedObsidian>, null, null, null, null],
[null, null, null, <ore:stone>, <DraconicEvolution:infusedObsidian>, <ore:stone>, null, null, null],
[null, null, <ore:slabStone>, <ore:slabStone>, <ore:slabStone>, <ore:slabStone>, <ore:slabStone>, null, null]]);

mods.avaritia.ExtremeCrafting.remove(<Avaritia:Infinity_Sword>);
mods.avaritia.ExtremeCrafting.addShaped(<Avaritia:Infinity_Sword>, [
[null, null, null, null, null, null, null, <ore:plateInfinity>, <TConstruct:largeSwordBlade:501>],
[null, null, null, null, null, null, <ore:plateInfinity>, <TaintedMagic:ItemPrimordialEdge>, <ore:plateInfinity>],
[null, null, null, null, null, <ore:plateInfinity>, <IC2:itemNanoSaber:1>, <ore:plateInfinity>, null],
[null, null, null, null, <ore:plateInfinity>, <ThaumicTinkerer:ichorSwordGem:*>, <ore:plateInfinity>, null, null],
[null, <TaintedMagic:ItemMaterial:5>, null, <ore:plateInfinity>, <Avaritia:Skull_Sword>, <ore:plateInfinity>, null, null, null],
[null, null, <TaintedMagic:ItemMaterial:5>, <DraconicEvolution:draconicDistructionStaff>, <ore:plateInfinity>, null, null, null, null],
[null, null, <ore:blockCosmicNeutronium>, <TaintedMagic:ItemMaterial:5>, null, null, null, null, null],
[null, <ore:blockCosmicNeutronium>, null, null, <TaintedMagic:ItemMaterial:5>, null, null, null, null],
[<Avaritia:Resource:5>, null, null, null, null, null, null, null, null]]);

// --- Nature's Ruin
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Infinity_Axe>);

// --- Longbow of the Heavens
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Infinity_Bow>);

// --- Planet Eater
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Infinity_Shovel>);


mods.avaritia.ExtremeCrafting.remove(<Thaumcraft:WandCasting:9000>.withTag({cap: "matrix", rod: "infinity"}));
mods.avaritia.ExtremeCrafting.addShaped(<Thaumcraft:WandCasting:9000>.withTag({cap: "matrix", rod: "infinity"}), [
[null, null, <ore:plateInfinity>, null, null, null, null, null, null],
[null, <ore:plateInfinity>, <ThaumicTinkerer:blockTalisman>, <ore:plateInfinity>, null, null, null, null, null],
[<ore:plateInfinity>, <TaintedMagic:ItemFocusTime>, <Avaritia:Resource:5>, <ore:plateCosmicNeutronium>, <AWWayofTime:dawnScribeTool>, null, null, null, null],
[null, <ore:plateInfinity>, <ore:plateCosmicNeutronium>, <Thaumcraft:WandCasting:150>.withTag({cap: "ICHOR", rod: "ICHORCLOTH", sceptre: 1}), <ore:plateCosmicNeutronium>, <AWWayofTime:waterScribeTool>, null, null, null],
[null, null, <AWWayofTime:duskScribeTool>, <ore:plateCosmicNeutronium>, <Thaumcraft:WandCasting:150>.withTag({cap: "ICHOR", rod: "ICHORCLOTH", sceptre: 1}), <ore:plateCosmicNeutronium>, <AWWayofTime:airScribeTool>, null, null],
[null, null, null, <AWWayofTime:fireScribeTool>, <ore:plateCosmicNeutronium>, <Thaumcraft:WandCasting:150>.withTag({cap: "ICHOR", rod: "ICHORCLOTH", sceptre: 1}), <ore:plateCosmicNeutronium>, <ore:plateInfinity>, null],
[null, null, null, null, <AWWayofTime:earthScribeTool>, <ore:plateCosmicNeutronium>, <Avaritia:Resource:5>, <TaintedMagic:ItemFocusTime>, <ore:plateInfinity>],
[null, null, null, null, null, <ore:plateInfinity>, <ThaumicTinkerer:blockTalisman>, <ore:plateInfinity>, null],
[null, null, null, null, null, null, <ore:plateInfinity>, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped(<Avaritia:Infinity_Bow>, [
[null, null, null, <ore:plateInfinity>, <ore:plateInfinity>, <TaintedMagic:ItemFocusMeteorology>, null, null, null],
[null, null, <ore:plateInfinity>, null, <ThaumicTinkerer:kamiResource:1>, null, null, null, null],
[null, <ore:plateInfinity>, null, null, <ThaumicTinkerer:kamiResource:1>, null, null, null, null],
[<ore:plateInfinity>, null, null, null, <ThaumicTinkerer:kamiResource:1>, null, null, null, null],
[<Avaritia:Resource:5>, null, null, null, <DraconicEvolution:draconicBow>, <TaintedMagic:ItemFocusTime>, null, null, null],
[<ore:plateInfinity>, null, null, null, <ThaumicTinkerer:kamiResource:1>, null, null, null, null],
[null, <ore:plateInfinity>, null, null, <ThaumicTinkerer:kamiResource:1>, null, null, null, null],
[null, null, <ore:plateInfinity>, null, <ThaumicTinkerer:kamiResource:1>, null, null, null, null],
[null, null, null, <ore:plateInfinity>, <ore:plateInfinity>, <TaintedMagic:ItemFocusMeteorology>, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped(<Avaritia:Infinity_Axe>, [
[null, <ore:plateInfinity>, null, null, null, null, null, null, null],
[<ore:plateInfinity>, <ForbiddenMagic:MorphAxe>, <ore:plateInfinity>, <ore:plateInfinity>, <ore:plateInfinity>, null, null, null, null],
[<ore:plateInfinity>, <ThaumicTinkerer:ichorAxeGem:*>, <DraconicEvolution:draconicAxe>, <ore:plateInfinity>, null, null, null, null, null],
[null, <ore:plateInfinity>, <ore:blockCosmicNeutronium>, null, null, null, null, null, null],
[null, null, <ore:blockCosmicNeutronium>, null, null, null, null, null, null],
[null, null, <ore:blockCosmicNeutronium>, null, null, null, null, null, null],
[null, null, <ore:blockCosmicNeutronium>, null, null, null, null, null, null],
[null, null, <ore:blockCosmicNeutronium>, null, null, null, null, null, null],
[null, <TaintedMagic:ItemFocusTime>, <Avaritia:Resource:5>, <TaintedMagic:ItemFocusTime>, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped(<Avaritia:Infinity_Shovel>.withTag({destroyer: 0 as byte}), [
[null, null, null, null, null, null, <ore:plateInfinity>, <ore:plateInfinity>, <ore:plateInfinity>],
[null, null, null, null, null, <ore:plateInfinity>, <ForbiddenMagic:MorphShovel>, <DraconicEvolution:draconicShovel>, <ore:plateInfinity>],
[null, null, null, null, null, null, <ThaumicTinkerer:ichorShovelGem:*>, <ForbiddenMagic:TaintShovel>, <ore:plateInfinity>],
[null, null, null, null, null, <ore:blockCosmicNeutronium>, null, <ore:plateInfinity>, null],
[null, null, null, null, <ore:blockCosmicNeutronium>, null, null, null, null],
[null, null, null, <ore:blockCosmicNeutronium>, null, null, null, null, null],
[null, <TaintedMagic:ItemFocusTime>, <ore:blockCosmicNeutronium>, null, null, null, null, null, null],
[<Avaritia:big_pearl>, <ore:blockCosmicNeutronium>, <TaintedMagic:ItemFocusTime>, null, null, null, null, null, null],
[<Avaritia:Resource:5>, <Avaritia:big_pearl>, null, null, null, null, null, null, null]]);

mods.avaritia.ExtremeCrafting.addShaped(<rftools:creativeDimensionBuilderBlock>, [[<rftools:infusedDiamondItem>, <rftools:infusedDiamondItem>, <customthings:item:13>, <customthings:item:13>, <GTFei:Plate3>, <customthings:item:13>, <customthings:item:13>, <rftools:infusedDiamondItem>, <rftools:infusedDiamondItem>],[<rftools:infusedDiamondItem>, <customthings:item:24>, <customthings:item:24>, <customthings:item:24>, <GTFei:Plate3>, <customthings:item:24>, <customthings:item:24>, <customthings:item:24>, <rftools:infusedDiamondItem>],[<customthings:item:54>, <customthings:item:54>, <customthings:item:54>, <customthings:item:54>, <GTFei:Plate3>, <customthings:item:54>, <customthings:item:54>, <customthings:item:54>, <customthings:item:54>],
[<Avaritia:Resource_Block:1>, <Avaritia:Resource_Block:1>, <Avaritia:Resource_Block:1>, <customthings:item:50>, <GTFei:Plate3>, <customthings:item:50>, <Avaritia:Resource_Block:1>, <Avaritia:Resource_Block:1>, <Avaritia:Resource_Block:1>],[<GTFei:Plate3>, <GTFei:Plate3>, <GTFei:Plate3>, <GTFei:Plate3>, <rftools:dimensionBuilderBlock>, <GTFei:Plate3>, <GTFei:Plate3>, <GTFei:Plate3>, <GTFei:Plate3>],[<Avaritia:Resource_Block:1>, <Avaritia:Resource_Block:1>, <Avaritia:Resource_Block:1>, <customthings:item:50>, <GTFei:Plate3>, <customthings:item:50>, <Avaritia:Resource_Block:1>, <Avaritia:Resource_Block:1>, <Avaritia:Resource_Block:1>],[<customthings:item:54>, <customthings:item:54>, <customthings:item:54>, <customthings:item:54>, <GTFei:Plate3>, <customthings:item:54>, <customthings:item:54>, <customthings:item:54>, <customthings:item:54>],[<rftools:infusedDiamondItem>, <customthings:item:24>, <customthings:item:24>, <customthings:item:24>, <GTFei:Plate3>, <customthings:item:24>, <customthings:item:24>, <customthings:item:24>, <rftools:infusedDiamondItem>],[<rftools:infusedDiamondItem>, <rftools:infusedDiamondItem>, <customthings:item:13>, <customthings:item:13>, <GTFei:Plate3>, <customthings:item:13>, <customthings:item:13>, <rftools:infusedDiamondItem>, <rftools:infusedDiamondItem>]]);

